spring:
  application:
    name: computing-service-producer
  profiles:
    active: producer0

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer0:8760/eureka/,http://peer1:8761/eureka/,http://peer2:8762/eureka/

---
spring:
  profiles: producer0
server:
  port: 8000
---

spring:
  profiles: producer1

server:
  port: 8001
---